name: Build & Push to Docker Hub

on:
  push:
    branches: [ "main" ]   # build every push to main
  workflow_dispatch:       # allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}

    # set up Buildx using your cloud builder
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: cloud
        endpoint: "beasthavoc/my-hub-builder"   # EXACT builder name you created
        install: true

    # build the image and push the 'latest' tag
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: beasthavoc/ai-workbench:latest
